#!/usr/bin/env bash
#
# smolofis-firstboot — idempotent per-device initialization.
#
# Installed into the image as /usr/local/bin/smolofis-firstboot and executed by
# smolofis-infrastructure.service (ExecStartPre) on every boot. It creates the
# persistent storage tracks under /var/lib/smolofis/ and generates the secrets
# the Coolify stack needs exactly once per device, so flashed images never
# share credentials.

set -euo pipefail

readonly STATE_ROOT="/var/lib/smolofis"
readonly CONF_ROOT="/etc/smolofis"
readonly SECRETS_FILE="${CONF_ROOT}/secrets.env"

log() { printf '[smolofis-firstboot] %s\n' "$*"; }

rand_hex() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }
rand_b64() { head -c "$1" /dev/urandom | base64 | tr -d '\n'; }

# ---------------------------------------------------------------------------
# Persistent storage tracks
# ---------------------------------------------------------------------------
log "ensuring persistent storage tracks under ${STATE_ROOT}"
install -d -m 0755 "${STATE_ROOT}"
install -d -m 0750 "${STATE_ROOT}/gitea"
install -d -m 0750 "${STATE_ROOT}/coolify"
install -d -m 0700 "${STATE_ROOT}/coolify/db"
install -d -m 0750 "${STATE_ROOT}/coolify/data"
install -d -m 0700 "${STATE_ROOT}/coolify/ssh"
install -d -m 0750 "${STATE_ROOT}/coolify/redis"

# ---------------------------------------------------------------------------
# Per-device secrets (generated once, then immutable)
# ---------------------------------------------------------------------------
install -d -m 0755 "${CONF_ROOT}"

if [[ -s "${SECRETS_FILE}" ]]; then
    log "secrets already provisioned at ${SECRETS_FILE} — leaving untouched"
else
    log "generating per-device secrets at ${SECRETS_FILE}"
    umask 077
    # compose env_file values are literal (no interpolation), so the shared
    # database password is expanded here and written to both keys.
    db_password="$(rand_hex 24)"
    cat > "${SECRETS_FILE}" <<EOF
# Generated by smolofis-firstboot on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Unique to this device. Deleting this file resets the Coolify stack's
# credentials and will orphan the existing database.
APP_KEY=base64:$(rand_b64 32)
APP_ID=$(rand_hex 16)
DB_PASSWORD=${db_password}
POSTGRES_PASSWORD=${db_password}
REDIS_PASSWORD=
PUSHER_APP_ID=$(rand_hex 8)
PUSHER_APP_KEY=$(rand_hex 16)
PUSHER_APP_SECRET=$(rand_hex 16)
EOF
    chmod 0600 "${SECRETS_FILE}"
fi

log "first-boot initialization complete"
